sources:
  - name: searches
    database: raw_nw_se
    schema: searches
    tables:
      - name: searches_data
  - name: applications
    database: raw_nw_se
    schema: applications
    tables:
      - name: applications_data